name: Build Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 7"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code from repository
      uses: actions/checkout@v2
    - name: Build and Push the image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: m75software/concrete5
        tag_with_ref: true
